version: "2"
services:
  nginx:
    image: nginx:alpine
    container_name: webserver
    volumes:
      - ./site:/usr/share/nginx/html
    ports:
      - "81:80"
    environment:
      - NGINX_HOST=alvitre.dev.local
      - NGINX_PORT=81
    networks:
      - site

  node:
    image: node:alpine
    container_name: nodejs
    restart: unless-stopped
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    networks:
      - site

networks:
  site:
    driver: bridge
