version: "2"
services:
  nginx:
    image: nginx:alpine
    container_name: webserver
    volumes:
      - ./site:/usr/share/nginx/html
    ports:
      - "8081:8081"
    environment:
      - NGINX_HOST=alvitre.net
      - NGINX_PORT=80
    networks:
      - site
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.ruleHost:alvitre.net"

  reverse-proxy:
    image: traefik
    command: --api --docker.exposebydefault=false
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./site:/usr/share/nginx/html

  node:
    image: node:alpine
    container_name: nodejs
    restart: unless-stopped
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    networks:
      - site

networks:
  site:
    driver: bridge
