version: "3"
services:
  nginx:
    image: nginx:alpine
    container_name: webserver
    volumes:
      - ./alvitre:/usr/share/nginx/html
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=alvitre.dev.local
      - NGINX_PORT=80
networks:
  default:
    external:
      name: nginx-proxy
