version: "3"
services:
  apache:
    image: "webdevops/apache"
    volumes:
      - "./vhost.conf:/opt/docker/etc/httpd/vhost.conf"
      - "../../site:/app/alvitre"
    ports:
      - "800:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alvitre.rule=Host(`apache.localhost`)"
      - "traefik.http.services.alvitre.loadbalancer.server.port=800"
