version: "2"

networks:
  alvitre:
    driver: bridge

services:
  apache:
    image: bitnami/apache:latest
    container_name: apache
    working_dir: /app
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - "./my_vhost.conf:/vhosts/my_vhost.conf:ro"
      - "../../site:/app/alvitre"
      - "../../../acolher/front/dist:/app/alvitre/acolher"
    networks:
      - alvitre

  mysql_acolher:
    image: mysql:8.0.1
    container_name: mysql_acolher
    restart: unless-stopped
    tty: true
    ports:
      - "2020:3306"
    environment:
      MYSQL_DATABASE: acolher
      MYSQL_USER: acolher
      MYSQL_PASSWORD: acolher
      MYSQL_ROOT_PASSWORD: acolher
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ../../../acolher/mysql:/var/lib/mysql
    networks:
      - alvitre

  php_acolher:
    build: .
    container_name: php_acolher
    working_dir: /usr/share/nginx/html
    volumes:
      - ../../../acolher/back:/usr/share/nginx/html
    command: "php artisan serve --host=0.0.0.0 --port=2030"
    ports:
      - "2030:2030"
    environment:
      PMA_HOST: mysql
    links:
      - "mysql_acolher"
    networks:
      - alvitre

  composer_acolher:
    image: composer:latest
    container_name: composer_acolher
    volumes:
      - ../../../acolher/back:/usr/share/nginx/html
    working_dir: /usr/share/nginx/html
    depends_on:
      - php_acolher
    networks:
      - alvitre
