version: "2"
services:
  nginx_acolher:
    image: "bitnami/apache:latest"
    ports:
      - "7081:8082"
    volumes:
      - "../../../acolher/front/dist:/app"
    environment:
      - APACHE_HTTP_PORT_NUMBER=8082
    labels:
      - "traefik.http.routers.nginx_acolher.rule=Host(`acolher.alvitre.net`)"
      - "traefik.http.services.nginx_acolher.loadbalancer.server.port=8082"
  mysql_acolher:
    image: mysql:8.0.1
    container_name: mysql_acolher
    restart: unless-stopped
    tty: true
    ports:
      - "2020:3306"
    environment:
      MYSQL_DATABASE: acolher
      MYSQL_USER: acolher
      MYSQL_PASSWORD: acolher
      MYSQL_ROOT_PASSWORD: acolher
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ../../../acolher/mysql:/var/lib/mysql
  php_acolher:
    build: .
    container_name: php_acolher
    working_dir: /usr/share/nginx/html
    volumes:
      - ../../../acolher/back:/usr/share/nginx/html
    command: "php artisan serve --host=0.0.0.0 --port=2030"
    ports:
      - "2030:2030"
    labels:
      - "traefik.http.routers.nginx_acolher.rule=Host(`backendacolher.alvitre.net`)"
      - "traefik.http.services.nginx_acolher.loadbalancer.server.port=2030"
    environment:
      PMA_HOST: mysql
    links:
      - "mysql_acolher"
  composer_acolher:
    image: composer:latest
    container_name: composer_acolher
    volumes:
      - ../../../acolher/back:/usr/share/nginx/html
    working_dir: /usr/share/nginx/html
    depends_on:
      - php_acolher
