version: "2"
networks:
  web:
    driver: bridge
services:
  php_apache:
    image: "webdevops/apache"
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./vhost.conf:/opt/docker/etc/httpd/vhost.conf"
      - "../../site:/app/alvitre"
    networks:
      web:
