version: "2"

services:
  php_apache:
    build: .
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./vhost.conf:/opt/docker/etc/httpd/vhost.conf"
      - "../../site:/var/www/html/alvitre"
      - "../../../acolher/front/dist:/var/www/html/alvitre/acolher"
      - "../../../acolher/back:/var/www/html/alvitre/backacolher"
      # - "../../../phpmyadmin:/var/www/html/alvitre/phpmyadmin"
    environment:
      PMA_HOST: mysql
    links:
      - mysql
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.1
    container_name: mysql
    restart: unless-stopped
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: acolher
      MYSQL_USER: acolher
      MYSQL_PASSWORD: acolher
      MYSQL_ROOT_PASSWORD: acolher
      SERVICE_NAME: mysql
    volumes:
      - ../../../acolher/mysql:/var/lib/mysql:rw,delegated

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_PASSWORD: acolher
      PMA_USER: acolher
    links:
      - mysql
    ports:
      - 8000:80
    depends_on:
      - mysql
  # php:
  # build: .
  # volumes:
  #   - "../../../acolher/back:/var/www/alvitre/backacolher"
  # ports:
  #   - "9000:9000"
  # environment:
  #   PMA_HOST: mysql
  # links:
  #   - "mysql_acolher"
  # networks:
  #   - alvitre
  # composer_acolher:
  #   image: composer:latest
  #   container_name: composer_acolher
  #   volumes:
  #     - ../../../acolher/back:/usr/share/nginx/html
  #   working_dir: /usr/share/nginx/html
  #   depends_on:
  #     - php
  #   networks:
  #     - alvitre
