version: "2"
services:
  # php_nginx:
  #   build: .
  #   volumes:
  #     - ../../../acolher/back:/app/acolher/back

  apache:
    image: bitnami/apache:latest
    container_name: apache
    working_dir: /app
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - "./my_vhost.conf:/vhosts/my_vhost.conf:ro"
      - "../../site:/app/alvitre"
      - "../../../acolher/front/dist:/app/alvitre/acolher"
