defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
    [entryPoints.https.auth.basic]
      users = ["jserranojunior:{SHA}s/KDLOda5hKbjBEmHOMS5WrWD5w="]
[web]
address = ":8080"
[acme]
email = "contato@alvitre.net"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
  [acme.httpChallenge]
    entryPoint = "http"
[[acme.domais]]
  main = "alvitre.net"
  sans = ["acolher.alvitre.net", "backendacolher.alvitre.net"]