version: "2"
services:
  apache:
    labels:
      - "traefik.http.routers.apache.rule=Host(`alvitre.localhost`)"
      - "traefik.http.services.apache.loadbalancer.server.port=8081"

  node:
    image: node:alpine
    container_name: nodejs
    restart: unless-stopped
    tty: true
    ports:
      - "3001:3000"
    volumes:
      - ../:/app
