version: "2"

networks:
  internal:
    driver: bridge

services:
  apache:
    container_name: "apache"
    image: "webdevops/apache"
    volumes:
      - "../src:/app"
    networks:
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.local.rule=Host(`localhost`,`alvitre.localhost`)"
      - "traefik.http.services.local.loadbalancer.server.port=80"

  apache_teste:
    container_name: "apache_teste"
    image: "webdevops/apache"
    volumes:
      - "../dist:/app"
    networks:
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.teste.rule=Host(`alvitre.teste.localhost`)"
      - "traefik.http.services.teste.loadbalancer.server.port=80"
