version: "2"

networks:
  internal:
    driver: bridge
services:
  apachealvitre:
    container_name: "apachealvitre"
    image: webdevops/apache
    restart: always
    volumes:
      # - "./vhost.conf:/opt/docker/etc/httpd/vhost.conf"
      - "../../src:/app"
    networks:
     - internal
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.sitealvitre.rule=Host(`www.alvitre.com.br`,`alvitre.com.br`)"
     - "traefik.http.services.sitealvitre.loadbalancer.server.port=80"

