version: "2"

networks:
  internal:
    driver: bridge
services:
    web:
      image: nginx
      container_name: "nginx_alvitre"
      volumes:
      - ../dist:/usr/share/nginx/html
      restart: always
      ports:
      - "2097:80"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.alvitre.rule=Host(`alvitre.net`,`www.alvitre.net`)"
        - "traefik.http.services.alvitre.loadbalancer.server.port=80"
  # apache:
  #   container_name: "nginx_alvitre"
  #   image: "webdevops/nginx"
  #   restart: always
  #   volumes:
  #     - "../dist:/app/alvitre"
  #   networks:
  #     - internal
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.alvitre.rule=Host(`alvitre.net`,`www.alvitre.net`)"
  #     - "traefik.http.services.alvitre.loadbalancer.server.port=80"


