version: "2"

networks:
  internal:
    driver: bridge
services:
    apachealvitre:
      container_name: "apachealvitre"
      image: "webdevops/apache"
      restart: always
      volumes:
      - "./vhost.conf:/opt/docker/etc/httpd/vhost.conf"
      - "../dist:/var/www/html/alvitre"
      restart: always
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.alvitre.rule=Host(`alvitre.com.br`,`www.alvitre.com.br`)"
        - "traefik.http.services.alvitre.loadbalancer.server.port=80"
  # apache:
  #   container_name: "nginx_alvitre"
  #   image: "webdevops/nginx"
  #   restart: always
  #   volumes:
  #     - "../dist:/app/alvitre"
  #   networks:
  #     - internal
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.alvitre.rule=Host(`alvitre.net`,`www.alvitre.net`)"
  #     - "traefik.http.services.alvitre.loadbalancer.server.port=80"


