import portfolio from "./assets/scripts/portfolio";
import isMobile from "./assets/scripts/isMobile";
import pwa from "./assets/scripts/pwa";
import togleMenu from "./assets/scripts/togleMenu";
import btnToTop from "./assets/scripts/btnToTop";
isMobile();
portfolio();
pwa();
togleMenu();
btnToTop();
