version: "2"

networks:
  internal:
    driver: bridge

services:
  apache:
    container_name: "apache"
    image: "webdevops/apache"
    restart: always
    volumes:
      - "../../src:/app"
    networks:
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.local.rule=Host(`alvitre.localhost`,`www.alvitre.localhost`)"
      - "traefik.http.services.local.loadbalancer.server.port=80"